name: freeroom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.22.0
  firebase_auth: ^3.11.0
  http: ^0.13.5
  cloud_firestore: ^3.5.1
  flutter_secure_storage: ^6.0.0
  firebase_database: ^9.1.7
  flutter_native_splash: ^2.2.9
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: "#071b5d"
  image: assets/images/Logo.png
  android: true
  ios: true

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf