// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc3I0Jmez-8V1Qun16cZ-HoPHh_Zp1gxk',
    appId: '1:834906989208:web:c2e1db70eaa464655ca6ed',
    messagingSenderId: '834906989208',
    projectId: 'freeroom-fa4a6',
    authDomain: 'freeroom-fa4a6.firebaseapp.com',
    storageBucket: 'freeroom-fa4a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-AKGBGyiD3uTSEWy8ppKx_Fec5xCrmSk',
    appId: '1:834906989208:android:2f092e71d1e1647a5ca6ed',
    messagingSenderId: '834906989208',
    projectId: 'freeroom-fa4a6',
    storageBucket: 'freeroom-fa4a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbtVD1f-EUrkNhjtodZclAs4krOnMME3U',
    appId: '1:834906989208:ios:e31e09bea42f0e7b5ca6ed',
    messagingSenderId: '834906989208',
    projectId: 'freeroom-fa4a6',
    storageBucket: 'freeroom-fa4a6.appspot.com',
    iosClientId: '834906989208-m7l1l0gs2600orp70nbv96kvaoctsbl1.apps.googleusercontent.com',
    iosBundleId: 'app.freeroom.freeroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbtVD1f-EUrkNhjtodZclAs4krOnMME3U',
    appId: '1:834906989208:ios:e31e09bea42f0e7b5ca6ed',
    messagingSenderId: '834906989208',
    projectId: 'freeroom-fa4a6',
    storageBucket: 'freeroom-fa4a6.appspot.com',
    iosClientId: '834906989208-m7l1l0gs2600orp70nbv96kvaoctsbl1.apps.googleusercontent.com',
    iosBundleId: 'app.freeroom.freeroom',
  );
}
